library(xlsx)
# library(deconstructSigs)
library(RSQLite)
library(tidyverse)
library(shiny)
library(rmarkdown)
library(knitr)
library(xtable)
library(jsonlite)

# vcfR
library(ape)
library(memuse)
library(pinfsc50)
library(vegan)